apiVersion: v1
kind: Service
metadata:
  name: {{ include "backstage.fullname" . }}
  namespace: backstage
  labels:
    app: {{ include "backstage.name" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "backstage.name" . }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
