{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: backstage
  labels:
    app: {{ include "backstage.name" . }}
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.serviceAccount.name }}-sa-token
  namespace: backstage
  annotations:
    kubernetes.io/service-account.name: {{ .Values.serviceAccount.name }}
type: kubernetes.io/service-account-token
{{- end }}
